
### REGISTER ###
POST localhost:9999/users
Content-Type: application/json

 {
 "fullName" : "Mihail Alexandrov" ,
 "password" : "abcdsA1526!" ,
 "confirmPassword" : "abcdsA1526!" ,
 "email" : "misho@abv.bg" ,
 "isAdmin" : false
 }



###
GET localhost:9999/users

###
 GET localhost:9999/users/1

###


