
##############################################      ADD CATEGORY     ##########################################
POST localhost:9999/categories
Content-Type: application/json

{
  "categoryName": "MAIL"
}


##############################################      EDIT CATEGORY     ##########################################
PUT localhost:9999/categories
Content-Type: application/json

{
  "oldName": "CD",
  "newName": "Television"
}

##############################################      FIND ALL  CATEGORIES    ##########################################
GET localhost:9999/categories
Content-Type: application/json

##############################################      DELETE CATEGORY     ##########################################
DELETE localhost:9999/categories
Content-Type: application/json


