### add category ###
POST localhost:9999/categories
Content-Type: application/json

{
  "categoryName": "CD"
}

### edit category ###
PUT localhost:9999/categories
Content-Type: application/json

{
  "oldName": "TV",
  "newName": "Television"
}

### find all categories ###
GET localhost:9999/categories
Content-Type: application/json

### delete category ###
DELETE localhost:9999/categories
Content-Type: application/json


