
#####################################################      ADD PRODUCT        ######################################
POST http://localhost:9999/products
Content-Type: application/json

{
 "name" : "sdfgdgf",
  "subCategoryId" : 2 ,
  "brand" : "so212" ,
  "model" : "212 31ode43dd5312324l" ,
  "price" : null,
  "quantity" : 2,
  "description" : "Sods321e 15125 product",
  "warrantyMonths" : 15
}

#####################################################      EDIT PRODUCT        ######################################
PUT http://localhost:9999/products/3
Content-Type: application/json

{
 "name" : "Some product",
  "subCategoryId" : 1 ,
  "brand" : "some brand" ,
  "model" : "some model" ,
  "price" : 0,
  "quantity" : 2,
  "description" : "Some stupid product",
  "warrantyMonths" : 15
}

#################################################      GET PRODUCT BY ID        ######################################
GET http://localhost:9999/products/1

#################################################      DELETE PRODUCT BY ID        ###################################
DELETE http://localhost:9999/products/16

#################################################      ADD PRODUCT TO FAV        ###################################
POST http://localhost:9999/products/2/fav

#################################################      REMOVE PRODUCT FROM FAV        ##############################
DELETE http://localhost:9999/products/2/fav

#####################################################      ADD DISCOUNT        ######################################
POST http://localhost:9999/discounts/2
Content-Type: application/json

{
  "discountPercent" : 25,
  "startDate" : "2022-02-25T16:42:00.000+00:00",
  "expireDate" : "2022-02-26T16:43:00.000+00:00"
}

###########################################      GET ALL PRODUCTS BY SUBCATEGORY        #############################
GET http://localhost:9999/subcategories/2/products

###########################################     GET ALL PRODUCTS BY SUBCATEGORY SORTED  #############################
GET http://localhost:9999/subcategories/products/price_desc

###########################################      SEARCH PRODUCTS BY KEYWORD        #############################
GET http://localhost:9999/products/search/prod

###########################################      GET ALL FAVOURITE PRODUCTS        #############################
GET http://localhost:9999/products/fav

################################################   GET PRODUCT WHERE PRICE IS BETWEEN ######################################
GET http://localhost:9999/subcategories/products/40/60

################################################   FILTER   ######################################
POST http://localhost:9999/products/filter
Content-Type: application/json

{
    "subcategoryId" : 8 ,
    "searchKeyword" : "product" ,
    "brand" : "so" ,
    "model" : "some" ,
    "maxPrice" : 600 ,
    "minPrice" : 200 ,
    "discountedOnly" : false ,
    "orderByPrice" : true ,
    "sortDesc" : false ,
    "productsPerPage" : 80 ,
    "pageNumber" : 1
}
