
#####################################################      ADD PRODUCT        ######################################
POST http://localhost:9999/products
Content-Type: application/json

{
 "name" : "Product 25",
  "subCategoryId" : 2 ,
  "brand" : "so" ,
  "model" : "some 31odel" ,
  "price" : 586.00,
  "quantity" : 2,
  "description" : "So321e stupid product",
  "warrantyMonths" : 15
}

#####################################################      EDIT PRODUCT        ######################################
PUT http://localhost:9999/products/3
Content-Type: application/json

{
 "name" : "Some product",
  "subCategoryId" : 1 ,
  "brand" : "some brand" ,
  "model" : "some model" ,
  "price" : 0,
  "quantity" : 2,
  "description" : "Some stupid product",
  "warrantyMonths" : 15
}

#################################################      GET PRODUCT BY ID        ######################################
GET http://localhost:9999/products/4

#################################################      DELETE PRODUCT BY ID        ###################################
DELETE http://localhost:9999/products/3

#################################################      ADD PRODUCT TO FAV        ###################################
POST http://localhost:9999/products/2/fav

#################################################      REMOVE PRODUCT FROM FAV        ##############################
DELETE http://localhost:9999/products/2/fav

#####################################################      ADD DISCOUNT        ######################################
POST http://localhost:9999/discounts/15
Content-Type: application/json

{
  "discountPercent" : 25,
  "startDate" : "2022-02-20T00:00:00.000+00:00",
  "expireDate" : "2022-04-28T00:00:00.000+00:00"
}

###########################################      GET ALL PRODUCTS BY SUBCATEGORY        #############################
GET http://localhost:9999/subcategories/2/products

###########################################     GET ALL PRODUCTS BY SUBCATEGORY SORTED  #############################
GET http://localhost:9999/subcategories/products/price_desc

###########################################      SEARCH PRODUCTS BY KEYWORD        #############################
GET http://localhost:9999/products/search/some

###########################################      GET ALL FAVOURITE PRODUCTS        #############################
GET http://localhost:9999/products/fav

################################################   GET PRODUCT WHERE PRICE IS BETWEEN ######################################
GET http://localhost:9999/subcategories/products/40/60
